doc/cvode/guide/source/Introduction.rst, doc/cvodes/guide/source/Introduction.rst
=> Correct recent changes for projection in CVODE(S)

CITATIONS.md, doc/arkode/guide/source/Landing.rst, doc/shared/cite_sundials.rst, doc/superbuild/source/index.rst
* Add citation for "Enabling new flexibility in the SUNDIALS suite of nonlinear and differential/algebraic equation solvers"
* Add citation for "ARKODE: A flexible IVP solver infrastructure for one-step methods"
=> Update sundials citations

CHANGELOG.md, doc/cvode/guide/source/Introduction.rst, doc/cvode/guide/source/Mathematics.rst, doc/cvode/guide/source/Usage/index.rst, doc/cvodes/guide/source/Introduction.rst, doc/cvodes/guide/source/Mathematics.rst, doc/cvodes/guide/source/Usage/SIM.rst, doc/ida/guide/source/Mathematics.rst, doc/ida/guide/source/Usage/index.rst, doc/idas/guide/source/Mathematics.rst, doc/idas/guide/source/Usage/SIM.rst
* Correct CVODE function names in recent changes and set function table
* Fix formatting of variables with underscores in subscript
=> Fix formatting and links in documentation

doc/arkode/guide/source/Usage/ARKStep_c_interface/User_callable.rst
Updated documentation for `ARKStepSetTables` to address concerns raised by ticket #195
=> Arkstep documentation update

src/ida/ida.c, src/idas/idas.c
Minor fixes to IDA(S) logging output
=> IDA(S) logging fixes

doc/cvode/guide/source/Usage/index.rst, doc/cvodes/guide/source/Usage/SIM.rst
=> #206: fix typo in docs 

src/sundials/sundials_logger.c
Just inserted some missing curly braces so that variable declaration is at top of block
=> Fix for C90 compilation error when logger enabled

examples/arkode/CXX_serial/ark_advection_diffusion_reaction.cpp, examples/arkode/CXX_serial/ark_advection_diffusion_reaction.hpp
* Add example option to adjust the CVODE max step size change after the first step
* Fix printing setup values for MRI+ARKStep
=> Update ARKODE ADR Example

README.md
... renders in GItHub properly with this change.
=> Fix math formatting in README

doc/cvode/guide/source/Usage/index.rst, doc/cvodes/guide/source/Usage/ADJ.rst, doc/cvodes/guide/source/Usage/SIM.rst, doc/ida/guide/source/Usage/index.rst, doc/idas/guide/source/Usage/SIM.rst
Fix some documentation errors and typos (addresses issue #280)
=> Documentation Fixes

CMakeLists.txt
=> append to CMAKE_MODULE_PATH instead of overwrite (#335)

.readthedocs.yaml
Add graphviz to Read the Docs config to display graphviz figures
=> Docs: Display graphviz figures

examples/sunmatrix/cusparse/test_sunmatrix_cusparse.cu, include/sundials/sundials_config.in, src/sunmatrix/cusparse/sunmatrix_cusparse.cu
* Fix cusparse matrix test 
* Fix scale add and scale add I functions for 1 x 1 matrix
=> Bugfix: cusparse matrix test

include/sundials/priv/sundials_mpi_errors_impl.h
Ref: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/6115528202
=> Fix SUNCheckMPICallNoRetMsg()

CITATIONS.md, doc/shared/cite_sundials.rst
Add volume, number, and pages to 2022 TOMS citation
=> Maintenance: update citation

cmake/macros/SundialsAddExamplesGinkgo.cmake, examples/sunlinsol/ginkgo/CMakeLists.txt, examples/sunlinsol/ginkgo/test_sunlinsol_ginkgo.cpp, examples/sunlinsol/ginkgo/test_sunlinsol_ginkgo_block.cpp, examples/sunmatrix/ginkgo/test_sunmatrix_gkoblock.cpp, include/sunlinsol/sunlinsol_ginkgo.hpp, include/sunlinsol/sunlinsol_ginkgoblock.hpp, include/sunmatrix/sunmatrix_ginkgo.hpp, include/sunmatrix/sunmatrix_ginkgoblock.hpp
This PR updates the existing (now old) ginkgo batched matrix format and solver interface with the new one that we already have in Ginkgo develop.
I put the base as `feature/ginkgo-batched`, but let me know if you would rather have it merged into your develop, but then I would need to rebase my branch on your develop.
This is still a WIP, as I am mostly co-developing kernels and features needed here in Ginkgo as well. See Ginkgo PR https://github.com/ginkgo-project/ginkgo/pull/1528, but I think this PR can already be looked at.
=> Update the ginkgo batched solvers interface

doc/shared/sundials/Install.rst
RE https://github.com/LLNL/sundials-private/issues/58. Add a section to the install guide on how to build sundials on Frontier.
=> Document installation procedure for Frontier

test/unit_tests/arkode/C_serial/CMakeLists.txt, test/unit_tests/arkode/C_serial/ark_test_mass.c
Replaces #375 which has become too outdated to easily merge develop into.
=> Add ARKODE unit test for number of mass matrix solves

CHANGELOG.md, doc/shared/RecentChanges.rst, src/sundials/CMakeLists.txt
=> Fix for #464

src/arkode/arkode_butcher.c
Fix copy-paste error in order condition 6s
=> Bugfix: order condition 6s

cmake/tpl/FindKLU.cmake
Revert changes to FindKLU made in #447
=> CMake: Revert KLU find_package updates

CHANGELOG.md, doc/shared/Changelog.rst, doc/shared/RecentChanges.rst, src/arkode/arkode_arkstep.c
Fixes a copy-paste error I made
=> Fix loading of default order 1 ERK method in ARKStep

examples/sunmatrix/ginkgo/test_sunmatrix_ginkgo.cpp
Fixes https://github.com/xsdk-project/xsdk-issues/issues/266.
=> fix missing semicolon

doc/shared/FAQ.rst
=> Docs: Fix typo in FAQ

.github/workflows/windows-latest-intel.yml
Update Intel compiler version to fix CI failures with Windows + Intel + Ninja
=> CI: Windows Intel Ninja Test

.github/workflows/docs-pdfs.yml, CHANGELOG.md, doc/kinsol/guide/source/Constants.rst, doc/kinsol/guide/source/Mathematics.rst, doc/kinsol/guide/source/Usage/index.rst, doc/shared/RecentChanges.rst, examples/kinsol/serial/CMakeLists.txt, examples/kinsol/serial/kinAnalytic_fp.c, examples/kinsol/serial/kinAnalytic_fp.out, examples/kinsol/serial/kinAnalytic_fp_--damping_fn.out, examples/kinsol/serial/kinAnalytic_fp_--damping_fp_0.5.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--damping_aa_0.5.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--damping_fn.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--delay_aa_2.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--orth_aa_1.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--orth_aa_2.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_2_--orth_aa_3.out, examples/kinsol/serial/kinAnalytic_fp_--m_aa_3_--depth_fn.out, include/kinsol/kinsol.h, src/kinsol/fmod_int32/fkinsol_mod.c, src/kinsol/fmod_int32/fkinsol_mod.f90, src/kinsol/fmod_int64/fkinsol_mod.c, src/kinsol/fmod_int64/fkinsol_mod.f90, src/kinsol/kinsol.c, src/kinsol/kinsol_impl.h, src/kinsol/kinsol_io.c, test/env/jenkins.sh, test/unit_tests/CMakeLists.txt
Add support in KINSOL for setting a user-supplied functions to compute the damping factor and depth in fixed-point or Picard iterations.
=> Feature: Anderson adaptive damping and depth

scripts/tarscript.sh
=> Bugfix: CVODE tarscript

doc/cvode/cv_ex_intro.tex
Thank you Alan Hindmarsh for the updates.
=> Update CVODE examples guide intro

.github/workflows/build-ci-containers-e4s.yml, .github/workflows/build-llvm-container.yml
Add concurrency to cancel already running jobs in container workflow. Copied from #737 by @willis89pr
=> CI: Add concurrency to containter workflows

.git-blame-ignore-revs
Update commit hash for python formatting upates
=> Maintenance: Update git blame ignore
