LLNL/sundials

benchmarks/nvector/cuda/test_nvector_performance_cuda.cu
benchmarks/nvector/mpiplusx/test_nvector_performance_mpiplusx.c
benchmarks/nvector/openmp/test_nvector_performance_openmp.c
benchmarks/nvector/openmpdev/test_nvector_performance_openmpdev.c
benchmarks/nvector/parallel/test_nvector_performance_parallel.c
benchmarks/nvector/parhyp/test_nvector_performance_parhyp.c
benchmarks/nvector/petsc/test_nvector_performance_petsc.c
benchmarks/nvector/pthreads/test_nvector_performance_pthreads.c

Some benchmarks already allowed for skipping these tests, this update makes the behavior consistent for all the vector benchmarks.
* If `nvecs < 1` skip all fused operation benchmarks
* If `nsums < 1` skip fused vector array operation benchmarks

Allow for skipping fused operation benchmarks

---

benchmarks/nvector/CMakeLists.txt
benchmarks/nvector/parhyp/test_nvector_performance_parhyp.c
benchmarks/nvector/test_nvector_performance.c

* Include `sundials_config.h` before using `SUNDIALS_HAVE_POSIX_TIMERS`
* Fix typo that prevented building hypre vector benchmarks

Bugfix: NVector benchmark timing

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
examples/arkode/C_serial/ark_kpr_mri.c
examples/arkode/F2003_serial/ark_kpr_mri_f2003.f90
examples/cvode/F2003_serial/cv_analytic_sys_dns_jac_f2003.f90
examples/cvode/serial/cvKrylovDemo_ls.c
examples/cvode/serial/cvParticle_dns.c
examples/cvodes/serial/cvsKrylovDemo_ls.c
examples/cvodes/serial/cvsParticle_dns.c
examples/nvector/manyvector/test_fnvector_manyvector_mod.f90
examples/sunlinsol/pcg/serial/test_fsunlinsol_pcg_mod_serial.f90
examples/sunlinsol/spbcgs/serial/test_fsunlinsol_spbcgs_mod_serial.f90
examples/sunlinsol/spfgmr/serial/test_fsunlinsol_spfgmr_mod_serial.f90
examples/sunlinsol/spgmr/serial/test_fsunlinsol_spgmr_mod_serial.f90
examples/sunlinsol/sptfqmr/serial/test_fsunlinsol_sptfqmr_mod_serial.f90
src/arkode/arkode_mri_tables.c
src/arkode/arkode_mristep.c
src/arkode/arkode_mristep_impl.h
src/cvode/cvode.c
src/cvodes/cvodes.c
test/unit_tests/arkode/C_serial/CMakeLists.txt
test/unit_tests/arkode/C_serial/ark_reset_check.c
test/unit_tests/ida/CXX_serial/ida_test_kpr.cpp
test/unit_tests/ida/C_serial/ida_test_getuserdata.c
test/unit_tests/idas/CXX_serial/idas_test_kpr.cpp
test/unit_tests/idas/C_serial/idas_test_getuserdata.c

* Fix memory leak in CVODE(S) when using projection
* Fix memory leak/out of bounds access in MRIStep when reinitializing and changing methods
* Fix memory leaks in various examples/tests

Bugfix: memory leaks

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
doc/ida/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
doc/kinsol/guide/source/Introduction.rst
examples/nvector/test_nvector.f90

Fix compilation error when building the serial NVector Fortran 2003 example with the Intel oneAPI 2022.2 Fortran compiler.

Bugfix: Intel oneAPI 2022.2 Fortran

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
doc/ida/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
src/arkode/arkode_root.c
src/cvode/cvode.c
src/cvodes/cvodes.c
src/ida/ida.c
src/idas/idas.c

This is a PR cherry picking https://github.com/novadiscovery/sundials/commit/f7a725e9964a4177b6055a972ff25fea48c404f0 to fix issue #57

Fix floating-point underflow during root finding in cvode and arkode

---

src/nvector/pthreads/CMakeLists.txt

With at least version 3.25.1 of cmake, the link line of the test_nvector_pthreads ends up so:
```
/usr/bin/cc -fcommon -Wl,-z,relro -Wl,-z,now CMakeFiles/test_nvector_pthreads.dir/test_nvector_pthreads.c.o ../CMakeFiles/test_nvector_obj.dir/test_nvector.c.o -o test_nvector_pthreads  -Wl,-rpath,/<<PKGBUILDDIR>>/debian/build/src/nvector/pthreads/fmod:/<<PKGBUILDDIR>>/debian/build/src/nvector/serial:/<<PKGBUILDDIR>>/debian/build/src/nvector/pthreads ../../../src/nvector/pthreads/fmod/libsundials_fnvecpthreads_mod.so.6.4.1 -lm -lpthread ../../../src/nvector/serial/libsundials_nvecserial.so.6.4.1 ../../../src/nvector/pthreads/libsundials_nvecpthreads.so.6.4.1
```
but that fails to link with:
```
/usr/bin/ld: ../../../src/nvector/pthreads/libsundials_nvecpthreads.so.6.4.1: undefined reference …
```

Fix link on non-Linux

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
doc/ida/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
doc/kinsol/guide/source/Introduction.rst
doc/shared/Install.rst
examples/sunlinsol/CMakeLists.txt
examples/sunlinsol/onemkldense/CMakeLists.txt
examples/sunmatrix/CMakeLists.txt
examples/sunmatrix/onemkldense/CMakeLists.txt

Fixes #251. The `icx` compiler will treat C files as C++ files when the `-fsycl` flag is present (the flag appears to be picked up when linking to oneMKL). This causes compilation failures due to C standard flags added by CMake. This only impacts the oneMKL matrix and linear solver examples and is addressed by using the separately compiled object library for the shared C test code.

Bugfix: SYLC example builds with C soruce

---

benchmarks/nvector/test_nvector_performance.c
src/arkode/arkode_arkstep.c

Fix uninitialized value warnings that show up in `Release` and `RelWithDebInfo` builds.

Fix initialization warnings

---

src/arkode/arkode_arkstep.c

Missing break when selecting ARKODE second order IMEX method

Add missing break

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
examples/arkode/CXX_serial/ark_heat2D.cpp
src/arkode/arkode.c

Fix a potential bug when constraint handling is enabled and `GetEstLocalErrors`is called in ARKODE

Bugfix: Constraint Temporary Vector Usage

---

doc/arkode/guide/source/conf.py
doc/cvode/guide/source/conf.py
doc/cvodes/guide/source/conf.py
doc/ida/guide/source/conf.py
doc/idas/guide/source/conf.py
doc/install_guide/source/conf.py
doc/kinsol/guide/source/conf.py
doc/shared/_templates/layout.html
doc/shared/sphinx_sundials.py
doc/superbuild/source/conf.py

* Move common extensions to shared file
* Updates index to group cmake options under "CMake options" category
* Update left navigation pane to include index link

Group CMake Options in index and Show index in left navigation pane

---

CHANGELOG.md
doc/cvodes/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
src/cvodes/cvodea.c
src/cvodes/cvodea_io.c
src/cvodes/cvodes_impl.h
src/idas/idaa.c
src/idas/idaa_io.c
src/idas/idas_impl.h

Fixes #333. Some other typedefs already had specialized (towards idas or cvodes) prefixed names, it won't harm to generalize this.

Change typedefs names to allow simulateous use of idas and cvodes

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
doc/ida/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
doc/kinsol/guide/source/Introduction.rst
src/sunlinsol/band/CMakeLists.txt
src/sunlinsol/cusolversp/CMakeLists.txt
src/sunlinsol/dense/CMakeLists.txt
src/sunlinsol/klu/CMakeLists.txt
src/sunlinsol/lapackband/CMakeLists.txt
src/sunlinsol/lapackdense/CMakeLists.txt
src/sunlinsol/pcg/CMakeLists.txt
src/sunlinsol/spbcgs/CMakeLists.txt
src/sunlinsol/spfgmr/CMakeLists.txt
src/sunlinsol/spgmr/CMakeLists.txt
src/sunlinsol/sptfqmr/CMakeLists.txt
src/sunlinsol/superludist/CMakeLists.txt
src/sunlinsol/superlumt/CMakeLists.txt
src/sunnonlinsol/fixedpoint/CMakeLists.txt
src/sunnonlinsol/newton/CMakeLists.txt

some libs are missing soversion, and this causes clients libs to link against full version instead:
xref https://github.com/conda-forge/assimulo-feedstock/issues/88
this doesnt look intentional because matching soversion macros are actually defined
cc @gardner48 @jmrohwer

Fix soversion ?

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
src/arkode/arkode_arkstep_io.c

Although we added a new low-order additive RK Butcher table pair, `ARKStepSetTableNum` did not recognize this as a valid ARK pair.  This fixes that issue.

bugfix-Support-ARK2-3-1-2

---

CHANGELOG.md
doc/arkode/guide/source/Introduction.rst
doc/cvode/guide/source/Introduction.rst
doc/cvodes/guide/source/Introduction.rst
doc/ida/guide/source/Introduction.rst
doc/idas/guide/source/Introduction.rst
doc/kinsol/guide/source/Introduction.rst
scripts/arkode
scripts/cvode
scripts/cvodes
scripts/ida
scripts/idas
scripts/kinsol
scripts/shared
src/arkode/arkode.c
src/cvode/cvode.c
src/cvodes/cvodes.c
src/ida/ida.c
src/idas/idas.c
test/unit_tests/arkode/C_serial/CMakeLists.txt
test/unit_tests/arkode/C_serial/ark_test_tstop.c
test/unit_tests/cvode/C_serial/CMakeLists.txt
test/unit_tests/cvode/C_serial/cv_test_tstop.c
test/unit_tests/cvodes/C_serial/CMakeLists.txt
test/unit_tests/cvodes/C_serial/cvs_test_tstop.c
test/unit_tests/ida/C_serial/CMakeLists.txt
test/unit_tests/ida/C_serial/ida_test_tstop.c
test/unit_tests/idas/C_serial/CMakeLists.txt
test/unit_tests/idas/C_serial/idas_test_tstop.c

Fixes #339: A regression was introduced by the stop time bug fix in v6.6.1 causing integrators to return at the stop time rather than the requested output time if the stop time was reached in the same step in which the output time was passed.
Also fixes a missing check in ARKODE to interpolate (or not) the solution at the stop time.

Bugfix: stop time and output time reached in same step

---

doc/arkode/guide/source/Usage/ARKStep_c_interface/User_callable.rst
doc/arkode/guide/source/Usage/ERKStep_c_interface/User_callable.rst
doc/arkode/guide/source/Usage/MRIStep_c_interface/User_callable.rst
doc/arkode/guide/source/Usage/SPRKStep_c_interface/User_callable.rst

Fix the description of `ONE_STEP` mode in ARKODE. The solution at the end of the step is always returned and interpolation is not performed.

Bugfix: ARKODE ONE_STEP Description

---

doc/shared/sundials/Install.rst
examples/utilities/custom_memory_helper_sycl.h
include/nvector/nvector_sycl.h
include/sundials/sundials_sycl_policies.hpp
include/sunlinsol/sunlinsol_onemkldense.h
include/sunmatrix/sunmatrix_onemkldense.h
include/sunmemory/sunmemory_sycl.h
src/nvector/raja/nvector_raja.cpp
src/nvector/sycl/nvector_sycl.cpp
src/sundials/sundials_sycl.h
src/sunmatrix/onemkldense/sunmatrix_onemkldense.cpp
test/unit_tests/sunmemory/sycl/test_sunmemory_sycl.cpp

The SYCL 2020 standard specifies `sycl/sycl.hpp` as the standard header to include however, implementations may still define the  old `CL/sycl.hpp` header for backwards compatibility. We already require SYCL 2020 but were still using the old header.

Maintenance: Use SYCL 2020 header

---

cmake/SundialsSetupTesting.cmake

Replace `FindPythonInterp` with `FindPython3`. The former was deprecated in CMake 3.12 and removed in 3.27, [CMP0148](https://cmake.org/cmake/help/v3.27/policy/CMP0148.html)

Bugfix: Replace use of FindPythonInterp

---

include/sundials/sundials_config.in

Remove unused `SUNDIALS_MPI_COMM_F2C` macro (originally needed in F77 interfaces).

Maintenance: Remove unused F77 macro

---

include/sundials/sundials_hip_policies.hpp

With newer versions of rocm, specifically 6.0.0, we have observed that the environment variable HIP_PLATFORM needs to be "amd". As a consequence, the WARP_SIZE goes undefined. I have spoken with AMD personnel, and they too suggest setting HIP_PLATFORM=AMD.

Update sundials_hip_policies.hpp to account for "amd" HIP_PLATFORM

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/arkode/arkode_sprk.c

ARKodeSPRKTable_Create did not allocate coefficient arrays

Bugfix: SPRK Table Create

---

.github/workflows/double-precision.yml
.github/workflows/extended-precision.yml
.github/workflows/single-precision.yml
.gitlab-ci.yml

Addresses https://hpc.llnl.gov/technical-bulletins/bulletin-568 and also limits our github action workflows to only run on push to certain branches.

use LC template for gitlab id tokens and limit github actions push events

---

.github/dependabot.yml

This is essentially the exact file that GitHub proposes here:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
Adding this file to the repository would simplify the update process of actions used in the CI.
You might need to additionally enable dependabot for this repository to actually make this work. You should be able to find that setting on the "Insights" tab in the "Dependency graph" section.
If it works, the bot will automatically create PRs for CI actions that are out of date. You can still decide to not merge those PRs. So everything will still be in your hands.
Potential caveat: This file might need to exist on the default branch of this repository (i.e., …

Use dependabot to periodically check for updated actions.

---

.github/workflows/windows-latest-mingw.yml

32-bit and 64-bit Windows systems are different to 32-bit and 64-bit Linux systems, e.g., when it comes to the data model.
Add a runner to the CI that builds for Windows 32-bit for coverage.

CI (MinGW): Add runner for 32-bit (MINGW32)

---

doc/developers
doc/superbuild/source/developers/index.rst
doc/superbuild/source/developers/style_guide/SourceCode.rst
doc/superbuild/source/developers/sundialsdev/index.rst
scripts/sundialsdev/__init__.py
scripts/sundialsdev/logs.py
src/arkode/arkode_arkstep.c
src/arkode/arkode_arkstep_nls.c
src/arkode/arkode_erkstep.c
src/arkode/arkode_mristep.c
src/arkode/arkode_mristep_nls.c
src/arkode/arkode_relaxation.c
src/cvode/cvode.c
src/cvodes/cvodes.c
src/kinsol/kinsol.c

I started this on another branch where I needed to parse the `SUNLogger` log files to understand (and plot) some CVode behavior.  The intent is to add more of our Python utilities for plotting stuff like step size over time etc.  We can also add other modules unrelated to logging.

Add a Python library for developer utilities with an initial module for log parsing

---

doc/shared/sundials/Install.rst

These also might need updating:
https://github.com/LLNL/sundials/blob/b685654c6958699821fc68a822b66076fec8cae7/cmake/macros/SundialsAddLibrary.cmake#L254-L257
https://github.com/LLNL/sundials/blob/f64d994640792801b089962beb526924cc57420d/.gitlab/spack_packages/sundials/package.py#L210-L211

Update CMake version in docs

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/nvector/sycl/nvector_sycl.cpp

This change was supposed to be reverted in #447 but it was missed. This will fix https://github.com/spack/spack/pull/44814#issuecomment-2185415334.

revert change to N_VSpace_Sycl that was missed

---

.git-blame-ignore-revs

Ignore recent revisions for Python and CMake formatting in git blame

Maintenance: update ignore revs

---

include/sundials/priv/sundials_errors_impl.h
src/sundials/sundials_errors.c
src/sundials/sundials_logger.c
test/unit_tests/sundials/test_sundials_errors.cpp

The `test_sundials_errors` test was failing for me which I traced down to the handling of variable arguments. It's the same issue discussed in https://github.com/LLNL/sundials/issues/461 which was partially fixed in https://github.com/LLNL/sundials/pull/462. This PR should finish it off.

Fix variable arguments start/end

---

doc/arkode/guide/source/Usage/MRIStep/User_callable.rst

When #439 was added, I forgot to update this documentation for `MRIStepSetOrder`.

Fix MRIStepSetOrder docs

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/arkode/arkode.c

The [docs](https://sundials.readthedocs.io/en/latest/arkode/Usage/User_callable.html#arkode-system-resize-function) state
> If a value hscale<=0 is specified, the default of 1.0 will be used

Make hscale=0 for ARKodeResize consistent with docs

---

CHANGELOG.md
cmake/tpl/FindKLU.cmake
doc/shared/RecentChanges.rst

Fixes a CMake configuration issue related to aliasing an ``ALIAS`` target when using ``ENABLE_KLU=ON`` in combination with a static-only build of SuiteSparse.
See #579 for details.
Fixes #579.

Fix aliasing potential `ALIAS` target `SuiteSparse::KLU`

---

doc/shared/sundials/SUNContext.rst

Fix indentation so the ordered list is enumerated correctly

Docs: Fix orderd list indentation

---

doc/superbuild/source/conf.py
doc/superbuild/source/developers/style_guide/Documentation.rst

Some recent PRs have included comments about stylistic inconsistencies in the documentation. This PR adds a style guide for documenting user-callable and user-supplied functions to hopefully reduce this kind of traffic in future PRs.

Doc: Add Function Documentation Style Guide

---

.github/workflows/check-format.yml
.github/workflows/check-spelling.yml
.github/workflows/check-swig.yml

Cancel running formatting, swing, and spelling checks on new pushes to prevent redundant failure messages

CI: Add concurrency in format/swig/spelling checks

---

include/arkode/arkode_erkstep.h
include/arkode/arkode_mristep.h

When moving the ARKODE user interface to a shared level and adding deprecation warnings to stepper-specific routines, some of the deprecation warnings seemed to have search/replace issues.  This PR fixes those.

Fixed erroneous deprecation warnings

---

cmake/SundialsSetupCuda.cmake

Updated CMake to prohibit CUDA interfaces when sunrealtype is set to extended precision.  Currently, this configuration just results in build failures later on, so this PR heads this off with a clear error message.

CUDA extended precision

---

CHANGELOG.md
benchmarks/advection_reaction_3D/raja/advection_reaction_3D.cpp
benchmarks/advection_reaction_3D/raja/advection_reaction_3D.hpp
benchmarks/advection_reaction_3D/raja/arkode_driver.cpp
cmake/SundialsSetupCompilers.cmake
doc/shared/RecentChanges.rst
examples/arkode/CXX_parallel/ark_brusselator1D.h
examples/arkode/CXX_parallel/ark_brusselator1D_task_local_nls.cpp
examples/arkode/C_parallel/ark_brusselator1D_task_local_nls.c
examples/cvodes/C_openmp/cvsAdvDiff_bnd_omp.c
examples/ida/C_openmp/idaFoodWeb_bnd_omp.c
examples/ida/C_openmp/idaFoodWeb_kry_omp.c
examples/ida/serial/idaFoodWeb_kry.c
examples/idas/C_openmp/idasFoodWeb_bnd_omp.c
examples/idas/C_openmp/idasFoodWeb_kry_omp.c
examples/idas/serial/idasRoberts_ASAi_klu.c
examples/idas/serial/idasRoberts_ASAi_sps.c
examples/idas/serial/idasRoberts_FSA_klu.c
examples/idas/serial/idasRoberts_FSA_sps.c
src/arkode/arkode_arkstep_impl.h
src/arkode/arkode_ls.c
src/cvode/cvode_proj.c
src/cvodes/cvodes_proj.c
src/ida/ida.c
src/idas/idas.c
src/sundials/sundials_logger.c
src/sunlinsol/sptfqmr/sunlinsol_sptfqmr.c
src/sunmatrix/sparse/sunmatrix_sparse.c

Tested new warning flags on gcc and clang. Not sure if this will work on Windows compilers (if that's something we intend to support)

Enable more warning flags which caught a couple small bugs

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/arkode/arkode_sprkstep.c
src/arkode/arkode_sprkstep_io.c

Fix a bug in SPRKStep where `yerr` was not initialized to zero when using compensated summations

Bugfix: Initialize yerr to zero

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/nvector/manyvector/fmod_int32/fnvector_manyvector_mod.c
src/nvector/manyvector/fmod_int32/fnvector_mpimanyvector_mod.c
src/nvector/manyvector/fmod_int64/fnvector_manyvector_mod.c
src/nvector/manyvector/fmod_int64/fnvector_mpimanyvector_mod.c
src/sunmatrix/band/fmod_int32/fsunmatrix_band_mod.c
src/sunmatrix/band/fmod_int64/fsunmatrix_band_mod.c
src/sunmatrix/dense/fmod_int32/fsunmatrix_dense_mod.c
src/sunmatrix/dense/fmod_int64/fsunmatrix_dense_mod.c
swig/nvector/fnvector_manyvector_mod.i
swig/nvector/fnvector_mpimanyvector_mod.i
swig/sunmatrix/fsunmatrix_band_mod.i
swig/sunmatrix/fsunmatrix_dense_mod.i

Add missing 32-bit ``sunindextype`` Fortran interface functions for
* ``N_VGetSubvectorArrayPointer_ManyVector``
* ``N_VGetSubvectorArrayPointer_MPIManyVector``
* ``SUNBandMatrix_Column``
* ``SUNDenseMatrix_Column``

Bugfix: Add missing int32 fortran functions

---

CHANGELOG.md
doc/shared/RecentChanges.rst
examples/arkode/C_serial/ark_kepler_--stepper_SPRK_--step-mode_fixed_--count-orbits_--use-compensated-sums.out
src/arkode/arkode.c
src/arkode/arkode_root.c

Fix a bug when enabling rootfinding with fixed step sizes and the initial value of the rootfinding function is zero. In this case, uninitialized right-hand side data (`fn`) is used to compute a forward Euler step to get a state near the initial condition to determine if any rootfinding functions are active at the initial condition.

Bugfix: Rootfinding with Fixed Step Size

---

doc/arkode/guide/source/Usage/LSRKStep/User_callable.rst
examples/arkode/CXX_manyvector/ark_sod_lsrk.cpp
examples/arkode/C_serial/ark_analytic_ssprk.c
include/arkode/arkode_lsrkstep.h
src/arkode/arkode_lsrkstep_io.c
src/arkode/fmod_int32/farkode_lsrkstep_mod.c
src/arkode/fmod_int32/farkode_lsrkstep_mod.f90
src/arkode/fmod_int64/farkode_lsrkstep_mod.c
src/arkode/fmod_int64/farkode_lsrkstep_mod.f90

Update set function name to be consistent with `SetNum` naming convention

Maintenance: Rename set function

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/arkode/arkode_arkstep.c
test/unit_tests/arkode/CXX_serial/ark_test_dahlquist_ark.cpp

Fix a bug in ARKStep where an extra right-hand side evaluation occurs each time step when enabling the ``ARKodeSetAutonomous`` option and using an IMEX method where the DIRK table has an implicit first and is not stiffly accurate. Fix a bug in counting the number of explicit RHS evaluations in the ARKStep Dahlquist unit test.

Bugfix: RHS eval logic with certain IMEX methods

---

README.md

Adding a status badge for the workflow that tracks our downloads in https://github.com/sundials-codes/sundials-download-tracker. This will make it readily apparent to us when there is an issue tracking downloads so we can minimize data loss. 
See https://github.com/sundials-codes/sundials-download-tracker/issues/1.

add sundials-downloads-tracker status badge

---

doc/shared/sundials/Install.rst
scripts/startReleaseCycle.sh
scripts/updateVersion.sh

Fix version numbers in the install guide 
Fix scripts to automatically update version numbers
Fix typo in version changed directive

Docs: Fix install guide versions

---

CHANGELOG.md
cmake/SundialsBuildOptionsPre.cmake
doc/shared/RecentChanges.rst

Fix the behavior of `SUNDIALS_ENABLE_ERROR_CHECKS` so additional runtime error checks are disabled by default with all release build types. Previously, `MinSizeRel` builds enabled additional error checking by default.

Bugfix: SUNDIALS_ENABLE_ERROR_CHECKS default value

---

README.md
doc/arkode/guide/source/Landing.rst
doc/arkode/guide/source/conf.py
doc/shared/latex/cover_pages.tex.txt
doc/superbuild/source/index.rst

This PR rectifies an omission from our last release, where we forgot to update the lists of SUNDIALS contributors to include Mustafa Aggul (who contributed the ARKODE LSRKStep module).

Mustafa-contributor

---

.github/workflows/docs-pdfs.yml

Add CI jobs to build PDFs for the user guides, example docs, and install guide

CI: Add jobs to test PDF doc builds

---

.github/workflows/check-format.yml
.github/workflows/check-spelling.yml
.github/workflows/check-swig.yml

Currently, our `/autofix` command does not work because the jobs don't have the 'write' permission.  This will fix it, but not until the change ends up in `main`.
This permission can be set globally too, but this is more secure.

Fix /autofix command

---

tools/suntools/logs.py

Not sure when this changed. Perhaps this is a sign we should have a test for the log parser.

Correct time label in log parser

---

.github/workflows/check-format.yml
.github/workflows/check-spelling.yml
.github/workflows/check-swig.yml
.github/workflows/test-address-sanitizer.yml
.github/workflows/ubuntu-clang-latest.yml
.github/workflows/ubuntu-latest.yml

Uniquely names artifacts for a matrix of jobs to so there's no conflicts like https://github.com/LLNL/sundials/actions/runs/13020815131/job/36320839738#step:7:16
The changes will allow us to get out files across all logging levels and precisions with on run rather than repeated runs and updates. That's been quite tedious on a couple recent PRs.
Any reason we can't remove limits like this:
https://github.com/LLNL/sundials/blob/2de70893c6360b0bb5047e86f3b0b882324c03fa/.github/workflows/ubuntu-latest.yml#L25

Simplify addressing of CI errors

---

examples/arkode/C_serial/ark_analytic_lsrk.c
examples/arkode/C_serial/ark_analytic_lsrk_varjac.c
examples/arkode/C_serial/ark_analytic_ssprk.c

Some of the `check_flag` calls in the LSRK examples were not returning the correct function names.

Fixing incorrect function name returns in check_flag calls

---

README.md
doc/shared/nvectors/NVector_Operations.rst

Fixed a typo in README and in a function input argument

fixed a typo in README and in a function input argument

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/arkode/arkode_mristep.c

A user identified that trying to resize an MRI method leads to the following error: `.../arkode_mristep.c:516][mriStep_Resize] Unable to resize vector`. The `arkResizeVecArray` returns a boolean for success or failure but it was being treated as a `SUNErrorCode`. It slipped though the cracks due to implicit conversions. I think this calls for more testing of resize, but for now here's a fix.

Bug fix for helper function return value when resizing MRI

---

.git-blame-ignore-revs

Ignore formatting updates from #699 in blame

Maintenance: Ignore python formatting in blame

---

doc/arkode/guide/source/Mathematics.rst

The default value was changed to `1.0` in v6.3.0 according to [here](https://sundials.readthedocs.io/en/latest/arkode/Usage/User_callable.html#c.ARKodeSetFixedStepBounds). [Code link](https://github.com/LLNL/sundials/blob/main/src/arkode/arkode_adapt_impl.h#L44).

fix default value of eta fixed step upper bound in arkode math section

---

.gitlab-ci.yml
.gitlab/jobs/tioga.yml
scripts/spack/packages/sundials/package.py

This updates spack version used in our GitLab CI testing so that we can use a newer version of Ginkgo.

update gitlab ci spack version and ginkgo version

---

.gitlab/build_and_test.sh
scripts/spack/packages/sundials/package.py
test/unit_tests/arkode/gtest/test_arkode_error_handling.cpp
test/unit_tests/cvode/gtest/test_cvode_error_handling.cpp
test/unit_tests/cvodes/gtest/test_cvodes_error_handling.cpp
test/unit_tests/ida/gtest/test_ida_error_handling.cpp
test/unit_tests/idas/gtest/test_idas_error_handling.cpp
test/unit_tests/kinsol/gtest/test_kinsol_error_handling.cpp

* Enable unit tests in GitLab CI with output comparisons disabled.
* Fix default logging level in spack package file
* Update error handler tests for different logging levels

CI: Enable unit tests in GitLab

---

examples/kinsol/serial/kinAnalytic_fp.c

Remove unused info file pointer in KiNSOL example. Copied from #738 by @VecoMr

Maintenance: Remove unused info file pointer

---

CHANGELOG.md
doc/shared/RecentChanges.rst
src/kinsol/kinsol.c
src/kinsol/kinsol_aa.c
test/unit_tests/kinsol/C_serial/CMakeLists.txt
test/unit_tests/kinsol/C_serial/kin_test_reuse_fp.c

* Initialize the Anderson acceleration depth every `KINSol` call
* Fix a logging bug where KINSOL logging messages would not be output

Bugfix: KINSOL initialize Anderson acceleration depth
